# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 1392b684ce69798efa08897cc04b023e27dff65c9276b55af01274490cf7fdd83716eb16e3e5a3583e90185b2c6d7eadf7d83d12b678ffb8ad813b9699b3491d

test:
  secret_key_base: 97b70dc084424da45ec72b3f41c6ea360cd0ece1e80e3091f1e43d3c5f0a991f8fd187b1518268b675f0d5860d0c24b909155da417954a4022c64bf6d267dcea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
